{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}-postgresql
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "misskey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
