{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}-redis
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "misskey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
