{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-postgresql
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ required "postgresql.password is required when postgresql.enabled=true and postgresql.existingSecret is not set" .Values.postgresql.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redis.enabled (not .Values.redis.existingSecret) .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-redis
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.postgresql.enabled) .Values.externalPostgresql.password (not .Values.externalPostgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-external-postgresql
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-external-redis
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redisForPubsub.enabled .Values.redisForPubsub.password (not .Values.redisForPubsub.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-redis-pubsub
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redisForPubsub.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redisForJobQueue.enabled .Values.redisForJobQueue.password (not .Values.redisForJobQueue.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-redis-jobqueue
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redisForJobQueue.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redisForTimelines.enabled .Values.redisForTimelines.password (not .Values.redisForTimelines.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-redis-timelines
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redisForTimelines.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redisForReactions.enabled .Values.redisForReactions.password (not .Values.redisForReactions.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}-redis-reactions
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redisForReactions.password | b64enc | quote }}
{{- end }}
