apiVersion: v2
name: emoji-bot-gateway
description: A Helm chart for Emoji Bot Gateway - Misskey Streaming API based emoji generation bot
type: application
version: 0.1.0
# renovate: image=ghcr.io/soli0222/emoji-bot-gateway
appVersion: "1.0.0"
