{{- $createAppSecret := not .Values.config.existingSecret }}
{{- $createPostgresSecret := and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
{{- if or $createAppSecret $createPostgresSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $createAppSecret }}
  SPOTIFY_CLIENT_ID: {{ .Values.config.spotifyClientId | b64enc | quote }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.config.spotifyClientSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{- if .Values.config.tokenEncryptionKey }}
  TOKEN_ENCRYPTION_KEY: {{ .Values.config.tokenEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.twitterClientId }}
  TWITTER_CLIENT_ID: {{ .Values.config.twitterClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.twitterClientSecret }}
  TWITTER_CLIENT_SECRET: {{ .Values.config.twitterClientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if $createPostgresSecret }}
  # If internal postgres is enabled and no secret provided, use 'spotify_password' as default
  {{ include "chart.postgres.secretKey" . }}: {{ .Values.postgres.auth.password | default "spotify_password" | b64enc | quote }}
  {{- end }}
{{- end }}
