{{- if and .Values.config.prometheus.enabled .Values.config.prometheus.password .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "navidrome.fullname" . }}-prometheus-auth
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "navidrome"
  password: {{ .Values.config.prometheus.password | quote }}
{{- end }}
