{{- if and .Values.config.prometheus.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "navidrome.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "navidrome.selectorLabels" . | nindent 6 }}
      {{- with .Values.serviceMonitor.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  endpoints:
    - port: http
      {{- if .Values.config.prometheus.metricsPath }}
      path: {{ .Values.config.prometheus.metricsPath }}
      {{- else }}
      path: /metrics
      {{- end }}
      {{- if .Values.config.prometheus.password }}
      basicAuth:
        username:
          name: {{ include "navidrome.fullname" . }}-prometheus-auth
          key: username
        password:
          name: {{ include "navidrome.fullname" . }}-prometheus-auth
          key: password
      {{- end }}
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
