apiVersion: v1
kind: Service
metadata:
  name: {{ include "distribution.fullname" . }}
  labels:
    {{- include "distribution.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.http.debug }}
    - port: {{ .Values.debugPort }}
      targetPort: debug
      protocol: TCP
      name: debug
    {{- end }}
  selector:
    {{- include "distribution.selectorLabels" . | nindent 4 }}
