{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey-summarizer.secretName" . }}
  labels:
    {{- include "misskey-summarizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  misskey-token: {{ .Values.secrets.misskeyToken | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
  discord-webhook-url: {{ .Values.secrets.discordWebhookUrl | quote }}
{{- end }}
