apiVersion: v2
name: misskey
description: A Helm chart for Misskey - A decentralized social networking platform
type: application
version: 0.1.0
# renovate: image=misskey/misskey
appVersion: "2025.12.2"
