{{- $createSpotifySecret := not .Values.config.existingSecret }}
{{- $createPostgresSecret := and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
{{- if or $createSpotifySecret $createPostgresSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotify-reblend.fullname" . }}
  labels:
    {{- include "spotify-reblend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $createSpotifySecret }}
  SPOTIFY_CLIENT_ID: {{ .Values.config.spotifyClientId | b64enc | quote }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.config.spotifyClientSecret | b64enc | quote }}
  {{- end }}
  {{- if $createPostgresSecret }}
  # If internal postgres is enabled and no secret provided, use 'reblend_password' (from example) as default
  {{ include "spotify-reblend.postgres.secretKey" . }}: {{ .Values.postgres.auth.password | default "reblend_password" | b64enc | quote }}
  {{- end }}
{{- end }}
