{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss-fetcher.fullname" . }}-webhooks
  labels:
    {{- include "rss-fetcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhooks.yaml: |
    webhooks:
    {{- toYaml .Values.config.webhooks | nindent 4 }}
{{- end }}
