apiVersion: v2
name: misskey-summarizer
description: A Helm chart for Misskey Summarizer CronJob
type: application
version: 0.1.1
# renovate: image=ghcr.io/soli0222/misskey-summarizer
appVersion: "1.0.1"
